modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="template"
version="1.0.0"
displayName="Template"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="MCreator"
description='''
MOD DESCRIPTION
'''

[[dependencies.template]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




